import Head from 'next/head'
import Box from '@mui/material/Box'
import Typography from '@mui/material/Typography'
import Layout from '@/containers/Layout/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hilton Hotel</title>
        <meta name="description" content="Generated by Hilton Hotel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Layout>
          <Box
            display="flex"
            justifyContent="center"
            alignItems="center"
            py={40}
          > */}
            <Typography variant="h3" component="h4">Home Page</Typography>
          {/* </Box>
        </Layout> */}
      </main>
    </>
  )
}
